version: 2
snapshot:
  widths:
    - 375 # minimum iPhone resolution
    - 810 # iPad
    - 1280 # desktop
  minHeight: 1024
  percyCSS: ""
static:
  include:
    - "index.html"
    - "/{about,contact,faq,glossary}/index.html"
    - "/{explore,focus}/**/index.html"
    - "/campaign/ABoVE/index.html"
    - "/instrument/CPL/index.html"
    - "/platform/Twin Otter/index.html"
  overrides:
    - files:
        - "index.html"
        - "/{about,contact,faq,glossary}/index.html"
        - "/{explore,focus}/**/index.html"
        - "/campaign/ABoVE/index.html"
        - "/instrument/CPL/index.html"
        - "/platform/Twin Otter/index.html"
      execute: "window.scrollTo(0, document.body.scrollHeight); setTimeout(()=>{window.scrollTo(0, -document.body.scrollHeight)}, 5000);"
      waitForTimeout: 2000
