repos:
-   repo: local
    hooks:
    -   id: eslint
        name: eslint
        entry: ./node_modules/.bin/eslint
        language: script
        types: [javascript]
        args: ["--ignore-path .gitignore /\"**/*.{js,jsx}\"", "--fix"]
        pass_filenames: true
        always_run: false
