name: Lint and Test

on: pull_request

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    env:
      
      ADMG_ACCESS_TOKEN: ${{ secrets.ADMG_ACCESS_TOKEN }}
      CYPRESS_password:	${{ secrets.CYPRESS_password }}
      GATSBY_ADMG_CLIENT_ID: ${{ secrets.GATSBY_ADMG_CLIENT_ID }}
      GATSBY_ADMG_CLIENT_SECRET: ${{ secrets.GATSBY_ADMG_CLIENT_SECRET }}
      GATSBY_CPU_COUNT: 1
      GATSBY_MAPBOX_TOKEN: ${{ secrets.MAPBOX_ACCESS_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Test End-to-end
        uses: cypress-io/github-action@v2
        with:
          start: yarn serve
          wait-on: 'http://localhost:8000'
