name: Lint and Test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      NODE: 22

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

  test:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      NODE: 22

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node modules
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: yarn install

      - name: Test
        run: yarn test
